### PR TITLE
Interactive Mode

### PR DESCRIPTION
**Pull request by bak**
Adds option -i to enter interactive review. Configure preferred command with code-review.command, default is "git log -p". Configure auto review with code-review.auto, default is to prompt user Y(es)/n(o)/l(ater).

### CODE REVIEW

**Comment by mackuba** [comment]
Looks good in general, I like the idea. I probably won't use this because I prefer GitHub's web UI, but I guess it could be useful for some people.

**Comment by bak** [comment]
Cool, thanks for the comments. I do more work on non-github repos than github, so I wanted to improve that end a bit :-)

**Comment by mackuba** [comment]
Hi, are you planning to make improvements based on my comments or did you leave that for me?

**Comment by bak** [comment]
Oh I'm looking for time to come back to it—we could get the API in there and come back to it later.

**Comment by mackuba** [comment]
Ok, no hurry, just wanted to check.

**Comment by bak** [comment]
I'm not using this tool anymore and won't have time to come back to this, so closing. Thanks!

**Pull request closed without merging**
